<!DOCTYPE html>
<html>
<head>
<title>Station of the cross</title>
<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
<div id="main">
<h1>STATION OF THE CROSS<br>View the station of the cross.</h1>

<button id="btn" onclick="myFunction()">Click to search</button><br> 

<a href="station of the cross.php" id="bk" class="back"><img src="img/back.png"></a>
<a href="Opening prayer.php" id="nt" class="next"><img src="img/forward.png"></a><br>
<body background="img/cross.jpg">
<img src="img/cross.jpg">
<p id="demo"></p>
</div>
<script>
function myFunction() {
  var text;
  var favPrayer = prompt("What is the?", "Opening prayer");
  switch(favPrayer) {
      case "Opening prayer":
      text = "V.  We adore you, and we bless you. <br> R. <b>Because by your holy cross you have redeemed the world.</i><br><br> <br>Let us pray:</b></i><br><br> God our Father, in obidence to you your only son accepted death on the Cross for the salvation of Mankind. We acknowledge the mistery of the cross on earth. May we recieve the gift of redemption in heaven. We ask this through Christ our Lord. Amen <br><br><br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br><br><br> <b>Hymn:</b>At the cross her her station keeping<br> stood the mournfull mother weeping<br> Close to Jesus to the last.";
      break;
      case "first station":
      text = "<h1>JESUS IS CONDEMNED TO DEATH</h1><br><br><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br><br><br>From the Gosple of St. John</b><br><br> Pilate was anxious to set him free, but the Jews shouted, If you set him free you are no friend of Caeser. hearing these words Pilate had Jesus brought out. Here is your King, he said to the Jews. Take him away, take him away! they said. Crucify him! Do you want me to Crucify your King? said Pilate. The chief priests answered, We haveno King except Caeser. So in the end Pilate handed him over to them to be Crucified. (Jn. 19: 12-13a, 15-16) <br><br><br> <b>Words of Our Lord<br><br>The Father loves me because i lay down my life in order to take it up again. No one takes it from me; I lay it down of my own free will, and as it is in my power to lay it down, so it is in my power to take it up again; and this is the command i have been given by my Father. (Jn.10: 17-18 )<br><br><br>Let us pray</b><br><br>Lord, by shedding his blood for us, your Son, Jesus Christ, established the Pascal mystery. In your goodness, make us holy and watch over us always. We ask this through Christ our Lord. Amen <br><br><br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br><br><br> <b>Hymn:</b> through her heart his sorrow sharing<br>All his bitter anguish bearing <br> Now at lenght the sword has passed";
      break;
      case "second station":
      text = "<h1>JESUS RECIEVES THE CROSS</h1><br> V. We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br><br><b> from the Gosple of St. John</b> They then took charge of Jesus, and carrying his own cross he went out of the city to the place of the skull or as it was called in Hebrew, Golgotha (Jn. 19: 17).<br><br><br> <b>words of Our Lord<br> <em>If anyone wants to be a follower of mine, let him renounce himself and take up his cross and follow me. For anyone who wants to save his life lose it: but anyone who loses his life will find it. What, then will a man gain if he wins the whole world and ruins his life? Or what has a man to offer in exchange for his life?</em> (Mt. 16: 24-26)<br><br>Let us pray:</b><br><br><br> Almighty and ever-living God, you gave our Saviour the command to become a man and undergo the cross, as an example for all men to follow. We have the lessons of his sufferings: give us also the fellowship of his resurrection. We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br><br> <b>Hymn:</b> Oh, how sad and sore distressed<br> Was that mother highly blest<br> Of the sole-begotten one.";
      break;
      case "third station":
      text = "<h1>JESUS FALL THE FIRST TIME UNDER HIS CROSS</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br> From the prophet Isaiah</b><br> The Lord Yahweh has opened my ear. For my part, I made no resistance, neither did i turn away. I offer my back to those who struck me, my cheeck to those who tore at my beard; I did not cover my face against insult and spittle. The Lord Yahweh comes to my help, so that i am untouched by the insults. So, too I set my face like flint; I know i shall not be shamed (Is. 50: 5-7). <br><b>Words of our Lord<em>I tell you, most solemnly, unless a wheat grain falls on the ground and dies, it remains only a single grain; but if it dies, it yeilds a rich havest. Anyone who loves his life loses it; anyone who hates his life in this world will keep it for the eternal life. Now my soul is troubed. What shall I say: Father, save me from this hour? But it was for this very reason that i have come to this hour. Father glorify your name!</em> (Jn. 12: 24-25; 27-28)<br>Let us pray:</b><br>Father, through the obidence of Jesus, your servant and your Son, you raised a fallen world. Free us from sin and bring us to the joy that last forever. We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> Christ above in torment hangs;<br>She beneath beholds the pangs<br> Of her dying glorious Son.";
      break;
      case "fourth station":
      text = "<h1>JESUS IS MET BY HIS BLESSED MOTHER</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br> From the Gosple of St. Luke</b><br> Simeon blessed them and said to Mary his mother, <em>You see this child: he is destined for the fall and for the rising of many in Israal, destined to be a sign that is rejected - and a sword will pierce your own soul too - so that the secret thoughts of many may be laid bare</em> (LK. 2: 34-35) <br><b>Words of Our Lord<br><em>I have come so that they may have life and have it to the full. i am the good shepherd; I know my own and my own knows me, just as the father knows me and i know the father; and i lay down my life for my sheep</em> (Jn. 10 10b, 14-15).<br>Let us pray</b><br> Father, you prepared the Virgin Mary to be worthy mother of your Son. You let her share before hand in the salvation Christ would bringby his death, and kept her sinless from the first moment of her being. help us by her prayers to live in your presence without sin. We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> Is there no one who would not weep<br>Whelm'd in miseries so deep,<br> Christ's dear mother to behold.";
      break;
      case "fifth station":
      text = "<h1>THE CROSS IS LAID UPON SIMON OF CYRENE</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br> From the Gosple of St. Mark</b><br>They enlisted a passer-by, Simon of Cyrene, Father of Alexander and Rufus, who was coming in from the country, to carry his cross (MK. 15: 21).<br><b>Words of Our Lord<br><em>The disciple is not superior to his teacher, nor the slave to his master, it is enough for the disciple that he should grow to be like his teacher, and the slave like his master. If they have called the master of the house Beelzebul, what will they not say of his household? Do not be afraid of those who kill the body but cannot kill the soul; fear him rather who can destroy both body and soul in hell</em> (Mt. 10: 24-25, 28).<br>Let us pray</b><br>Father, by the blood of your own Son you have set all men free and saved us from death. Continue your work of love within us, that by constantly ceebrating the mystery of salvation we may reach the enternal life it promises. We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> Can the human heart refrain<br>From partaking in her pain,<br>in that mother's pain untold";
      break;
      case "sixth station":
      text = "<h1>VERONICA WIPES THE FACE OF JESUS</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br> From the Prophet Isaiah</b><br> Who would believe what we have heard, and to whom has the power of Yahweh been revealed? Like a sapling he grew up in front of us, like a root in arid ground. Without beauty, without majesty we say him, no looks to attract our eyes: a thing despise and rejected by men, a man of sorrow and familiar with suffering, a man to make people screen their faces: he was despised and we took no account of him. (Is. 53: 1-3)<br><b>Words of Our Lord</b><br><em>Whoever sees me, sees who sent me. I, the light, have come into the world, so that Whoever believes in me need not stay in dark any more.</em>(Jn. 12: 45-46)<br>Let us pray:</b>God our Father, no secret is hidden from you, for ever heart is open to you and every wish is known. Fill our hearts with the light of your Holy Spirit to free our thoughts from sin, that we may perfectly love you and fittingly praise you. We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> Bruised, derided, cursed, defiled,<br>She beheld her tender child,<br>All with bloody scourges rent.";
      break;
      case "seventh station":
      text = "<h1>JESUS FALLS THE SECOND TIME</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br> From the Prophet Isaiah</b>And yet ours were the the sufferings he bore, ours the sorrows he carried. But we, we thought of him as someone punished struck by God, and brought low. Yet he was pierced through for our faults, crushed for our sins. On him lies a punishment that brings us peace, and through his wounds we are healed. We had all gone astray like sheep each taking his own way, and Yahweh burdened him with the sins of all of us.<b>Words of Our Lord<br><em>Be like men who are waiting for their master to return from the wedding feast, ready to open the door as soon as he comes and knocks.Happy those servants whom the master finds awake when he comes. You too must stand ready, because the Son of Man is coming at an hour you do not expect</em>(Lk. 12: 36-37; 40).<br> Let us pray:</b><br>Almighty God, grant that we who are constantly betrayed by our own weakness, may draw the breath of new life from the passion and death of your begotten Son. We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> For the sins of his own nation,<br>Saw him hang in desolation,<br>Till his spirit forth he sent.";
      break;
      case "eight station":
      text = "<h1>THE WOMEN OF JERUSELEM MOURN FOR OUR LORD</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br> From the Gosple of St. Luke</b><br>Large numbers of people followed him, and of women too, who mourned and lamented for him. But Jesus turned to them and said. <em>Daughters of Jeruselem, do not weep for me: weep rather for yourselves and for your children. For the days will surely come when people will say, <em>Happy are those who are barren, the wombs that have never borne, the breasts that have never suckled!</em>Then they will begin to say to the mountains, <em>Fall on us!</em>: to the hills,<em>Cover us!</em> For if men use the green wood like this, what will happen when it is dry?</em>(Lk. 23: 27-31).<br><b>Words of Our Lord<br><em>Happy those eho mourn: they shall be comforted. Happy those who are persecuted in the cause of right: theirs is the kingdom of heaven. Happy are you when people abuse you and persecute you and speak all kinds of calumny against you on my account. Rejoice and be glad, for your reward will be great in heaven.</em>(Mt. 5 5, 10-46)<br>Let us pray:</b><br> Father, help us to be like Christ your Son, who loved the world and died for our salvation. Inspire us by his love, guide us by his example. We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> O thou mother!  Fount of love!<br>Touch my spirit from above.<br>Make my heart with thine accord.";
      break;
      case "ninth station":
      text = "<h1>JESUS FALLS THE THIRD TIME</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br> From the Prophet Isaiah</b><br> By force and by law he was taken: would anyone plead his cause? Yes, he was torn away for the land of living; for our faults struck down in death. They gave him a grave with the wicked, a tomb with the rich, though he had done no wrong and there had been no perjury in his mouth. Yahweh had been pleased to crush him with suffering. If he offers his like in atonement, he shall see his heirs, he shall have a long life and through him what Yahweh wishes will be done(Is. 53: 8-10).<br><b>Words of Our Lord<em>Come to me, all you who labour and are overbudened, and i will give you rest. Shoulder my yoke and learn from me, for I am gentle and humble of heart, and you wil find rest for your souls. Yes, my yoke is easy and my burden light</em>(Mt. 11 28-30).</b><br> Let us pray:<br>Lord, may the suffering and death of Jesus, your only Son, make us pleasing to you. Alone we can do nothing, but may his perfect sacrifice win us your mercy and love. We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> Make me feel as thou hast felt:<br> Make my soul to glow and melt<br>With the love of Christ my Lord.";
      break;
      case "tenth station":
      text = "<h1>JESUS IS STRIPPED OF HIS GARMENTS</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br> From the Gosple of St. John</b> When the soldiers had finished crucifying Jesus they took his clothing and divided it into four shares one for each soldier. His undergarment was seamless, woven in one piece from neck to hem; so they said to one another, <em>instead of tearing it, let's throw dice to decide who is to have it.</em> In this way the words of Scripture were fulfilled: <em>They shared out my clothing amoung they. They cast lots for my clothes.</em> This is exactly what the soldiers did (Jn. 19: 23-24).<br><b>Words of Our Lord<br><em>I have come to bring fire to the earth, and how i wish it were blazing already! There is a baptism I must still recieve, and how great is my distress till it is over!</em>(Lk. 12: 49-50)<br>Let us pray:<br>Lord, by the suffering of Christ your Son you have saved us all from the death we inherited from sinful Adam. By the law of nature we have borne the likeness of his manhood. May the sanctifying power of grace help us to put on the the likeness of our Lord in heaven.</b> We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> Holy Mother, pierce me through,<br> In my hearth each wound renew <br> Of my Saviour Crucified.";
      break;
      case "elevent station":
      text ="<h1>JESUS IS NAILED ON THE CROSS</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br>From the Gosple of St. John</b><br>There they Crucified him with two others, one on either side with Jesus in the middle. Pilate wrote a notice and had it fixed to the cross; it ran <em>Jesus the Nazarene, King of the Jews</em>(Jn. 19: 18-20).<br><b>Words of Our Lord<br><em>When you have lifted up the Son of Man, then you will know that i am He and that i do nothing of myself: what the Father has taught me is what i preach. Now sentence is being passed on this world; now the prince of this world is to be overthrown. And when I am lifted up from the earth, I shall draw all men to myself</em>(Jn. 8: 28; 12: 31-32).<br>Let us pray<br></b>By your will, Lord God, your Son underwent the agony of the cross to break the power of Satan over man. Give your people grace to rise again with Christ.</b> We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> Let me share with thee his pain<br>Who for all my sins was slain<br>Who for me in torments died.";
      break;
      case "twelfth station":
      text = "<h1>JESUS DIES ON THE CROSS</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br>From the Gosple of St. John</b><br>Jesus knew that everything had now been completed, and to fulfill the scripture perfectly he said: <em>I am thirsty</em>. A jar full of vinegar stood there, so putting a sponge soaked in vinegar on a hyssop stick they held it upto his mouth. After Jesus had finished taking the vinegar he said, <em>It is accomplished</em>; and bowing his head he gave up  his spirit.(Jn. 17: 1, 4-6)<br><b>Words of Our Lord<br><em>Father, the hour has come: glorify your Son so that your Son may glorify you. I have glorified you on earth and finished the work that you gave me to do. Now, Father, it is time for you to glorify me with that glory I had with you before the world was</em>.(Jn. 17: 1, 4-6).<br>Letus pray:</b><br> Father of mercy, in your great love for us you have given us your only Son. May he take us up into his perfect sacrifice, that we may offer you fitting worship. </b> We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> Let me mingle tears with thee<br>Mourning him who mourned for me<br> All the days that i may live.";
      break;
      case "thirteenth station":
      text = "<h1>JESUS IS TAKEN DOWN FROM THE CROSS</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br> From the Gosple of St. John</b><br>After this, Joseph of Arimathea. who was a disciple of Jesus -though a secret one because he was afraid of the Jews - asked Pilate to let him remove the body of Jesus. Pilate gave permission, so they came and took it away. Nicodemus came as well - the same one who had first come to Jesus at night-time - and he brought a mixture  of myrrh and aloes, weighing about a hundred pounds. (Jn. 19: 38-39).<br><b>Words of Our Lord<br><em>I pray for them; I am not praying for the world but for those who you have given me, because they belong to you: all I have is yours, and all you have is mine, and in them I am glorified. I am not in the world any longer, but they are in the world, and I am coming to you. Holy Father, so that they may be one like us</em>.(Jn. 17: 9-11).<br> Let us pray:</b><br>Father, as your Son was raised on the cross, his mother Mary stood by him, sharing his sufferings. May your church be united with Christ in his sufferings and death and so come to share in his rising to new life.</b> We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> By the cross with thee to stay,<br> There with thee to weep and pray,<br>Is all i ask of thee to give.";
      break;
      case "fourteenth station":
      text = "<h1>JESUS IS PLACED IN THE SEPULCHRE</h1><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br> From the Gosple of St. John</b><br>They took the body of Jesus and wrapped it with the spices in limen clothes, following the Jews burial custom. At the place where he had been Crucified there was a garden, and in this garden a new tomb in which no one had yet been buried. Since it was the Jewish Day of Preparation and the tomb was near at hand, they laid Jesus there. (Jn. 19: 40-42).<br><b>Words of Our Lord<br><em>I pray not only for these, but for those also who through their words will believe in me. May they be one in us, as you are in me and i am in you, so that the world may believe it was you who sent me</em>.(Jn. 17: 20-21).<br>Let us pray:</b><br>Lord God, the creation of man was a wonderfull work, and his redemption still more wonderfull. May we persevere in right reason against all that entices to sin and to attain to everlasting joy.</b> We ask this through Christ our Lord. Amen <br> V. Have mercy on us, O Lord!<br> R. <b>Have mercy on us</b><br> <b>Hymn:</b> While my body here decays <br> May my soul they goodness praise, <br> Safe in paradise with thee. Amen";
      break;
      case "fifteenth station":
      text = "<h1>THE RISING OF JESUS FROM THE TOMB</h1><br><b>(This further station may be added to complete the story of the Paschal mystery).</b><br> V.  We adore you, and we bless you. <br> R.<b>Because by your holy cross you have redeemed the world.<br>"
      break;  
    default:
      text = "There is no station like that.";
  }
  document.getElementById("demo").innerHTML = text;
}
</script>


</body>
</html>